name: network_inspector
description: Http inspector / logger for Dio and Http package. This package would allow you to log every Http request, response, and error from Dio & Http.
version: 1.1.2
homepage: https://github.com/Meruya-Techhnology/network_inspector

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  dio: ^5.1.0
  sqflite: ^2.4.1
  sqflite_common: ^2.5.4
  sqflite_common_ffi_web: ^0.4.2
  provider: ^6.0.5
  intl: ^0.18.1
  analyzer: ^5.13.0
  collection: ^1.17.2
  share_plus: ^7.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/json/
    - assets/ffi/
